import { Project, ProjectId } from "../types";

const projects: Project[] = [
  {
    id: "coeus",
    name: "Coeus",
    title: "Coeus: Accelerating Scientific Insights Using Enriched Metadata",
    shortDescription:
      "In collaboration with Sandia and Oak Ridge National Laboratories, coeus investigate the use of an active storage system to calculate derived quantities and support complex queries on scientific data (simulation and observational) as well as optimizing data placement across the storage hierarchy, with awareness of the resource limitations, to better support the scientific discovery process.",
    link: "/research/projects/coeus",
    isFeatured: true,
    isOurs: true,
    researchStatus: "r&d",
    status: "active",
    type: "funded",
  },
  {
    id: "chronolog",
    name: "ChronoLog",
    title:
      "ChronoLog: A High-Performance Storage Infrastructure for Activity and Log Workloads",
    shortDescription:
      "HPC applications generate more data than storage systems can handle, and it is becoming increasingly important to store activity (log) data generated by people and applications. ChronoLog is a hierarchical, distributed log store that leverages physical time to achieve log ordering and reduce contention while utilizing storage tiers to elastically scale the log capacity.",
    link: "/research/projects/chronolog",
    isFeatured: true,
    isOpenSource: true,
    isOurs: true,
    researchStatus: "testing",
    status: "active",
    type: "funded",
  },
  {
    id: "iris",
    name: "IRIS",
    title: "IRIS: I/O Redirection Via Integrated Storage",
    shortDescription:
      "Various storage solutions exist and require specialized APIs and data models in order to use, which binds developers, applications, and entire computing facilities to using certain interfaces. Each storage system is designed and optimized for certain applications but does not perform well for others. IRIS is a unified storage access system that bridges the semantic gap between filesystems and object stores.",
    link: "/research/projects/iris",
    isFeatured: false,
    isOpenSource: true,
    isOurs: true,
    researchStatus: "testing",
    status: "active",
    type: "funded",
  },
  {
    id: "hermes",
    name: "Hermes",
    title:
      "Hermes: Extending the HDF Library to Support Intelligent I/O Buffering for Deep Memory and Storage Hierarchy System",
    shortDescription:
      "To reduce the I/O bottleneck, complex storage hierarchies have been introduced. However, managing this complexity should not be left to application developers. Hermes is a middeware library that automatically manages buffering in heterogeneous storage environments.",
    link: "/research/projects/hermes",
    isFeatured: true,
    isOpenSource: true,
    isOurs: true,
    researchStatus: "ready",
    status: "active",
    type: "funded",
  },
  {
    id: "labios",
    name: "Labios",
    title: "LABIOS: A Distributed Label-Based I/O System",
    shortDescription:
      "HPC and Big Data environments have diverged over the years, resulting in diverging and even conflicting I/O requirements. Labios aims to address the challenges vital to HPC + Big Data Convergence",
    link: "/research/projects/labios",
    isFeatured: false,
    isOurs: true,
    researchStatus: "r&d",
    status: "active",
    type: "funded",
  },
  {
    id: "dtio",
    name: "DTIO",
    title: "DTIO: A Data Task I/O Runtime",
    shortDescription:
      "In partnership with Argonne National Laboratory, DTIO investigates the use of a task framework for unifying complex I/O stacks and providing features such as resilience, fault-tolerance, and task replay.",
    link: "/research/projects/dtio",
    isFeatured: false,
    isOurs: true,
    researchStatus: "testing",
    status: "active",
    type: "funded",
  },
  {
    id: "viper",
    name: "Viper",
    title:
      "Viper: A High-Performance I/O Framework for Transferring Deep Neural Network Models",
    shortDescription:
      "Within a DL workflow, exchanging DNN models through PFS may result in  high model update latency and discovery latency. Moreover, model update frequency affects both training and inference performance. Viper is an I/O framework aiming to accelerate model discovery and delivery, and to find an optimal model checkpoint schedule to balance the trade-off.",
    link: "/research/projects/viper",
    isFeatured: false,
    // isOpenSource: false,
    isOurs: true,
    researchStatus: "r&d",
    status: "active",
    type: "funded",
  },
  {
    id: "dayu",
    name: "DaYu",
    title:
      "DaYu: Optimizing Workflow Performance by Elucidating Semantic Data Flow",
    shortDescription:
      "Nowadays, distributed scientific workflows encounter challenges in data movement through storage systems. DaYu, by capturing the mapping of data objects to I/O operations, can uncover new insights for optimizing workflow data movement.",
    link: "/research/projects/dayu",
    isFeatured: false,
    isOpenSource: true,
    isOurs: true,
    researchStatus: "testing",
    status: "active",
    type: "funded",
  },
  {
    id: "wisio",
    name: "WisIO",
    title:
      "WisIO: Automated I/O Bottleneck Detection via Multi-Perspective Views for HPC Workloads",
    shortDescription:
      "Explore WisIO, an automated I/O bottleneck detection tool with multi-perspective views for I/O trace data analysis. Overcoming large-scale I/O challenges, WisIO utilizes distributed computing and an extensible rule engine for tailored solutions. Elevate your I/O analysis in HPC environments with WisIO.",
    link: "/research/projects/wisio",
    isFeatured: false,
    isOpenSource: false,
    isOurs: true,
    researchStatus: "r&d",
    status: "active",
    type: "student",
  },
];

export default projects;

export function getProjectById(id: ProjectId): Project | undefined {
  return projects.find((project) => project.id === id);
}
